
name: Build
on: [push, pull_request]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6

      - name: Restore 
        run: dotnet restore src/sample.app.sln

      - name: Build Fody
        run: dotnet build --configuration Release --no-restore src/sample.app.sln

      - name: Test Fody
        run: dotnet test --configuration Release --no-build src/sample.app.sln

      - name: Upload NuGet
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: nugets/*.nupkg

  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6

      - name: Restore Fody
        run: dotnet restore src/sample.app.sln

      - name: Build Fody
        run: dotnet build --configuration Release --no-restore src/sample.app.sln

      - name: Test Fody
        run: dotnet test --configuration Release --no-build src/sample.app.sln

  windows-vs:
    name: Windows VS
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1.2

      - name: Build Fody
        run: msbuild -restore src/sample.app.sln /p:Configuration=Release /verbosity:minimal

      - name: Test Fody
        run: vstest.console src\sample.app.test\bin\Debug\net6.0\sample.app.test.dll